// src/components/sections/articles/components/article-card.svelte
<script lang="ts">
    export let title: string = "";
    export let description: string = "";
    export let date: string = "";
    export let image: string = "";
    export let author: string = "";
</script>

<div
    class="articles relative h-fit w-full border-2 border-gray-200 hover:border-blue-500 transition-all duration-300 rounded-xl p-1.5"
>
    <img class="w-full h-full object-cover rounded-lg" src={image} alt="" />
    <div class="p-4 flex flex-col gap-3">
        <div class="flex flex-col gap-1">
            <div
                class="bg-wri-gray-200 w-fit rounded-md px-1 py-0.5 text-wri-gray-600 text-base"
            >
                {date}
            </div>
            <div class="text-bold text-2xl">
                {title}
            </div>
        </div>
        <div class=" text-wri-gray-600 text-xl">
            {description}
        </div>
        <div class=" text-wri-gray-500 text-sm">
            by {author}
        </div>
    </div>
</div>

// src/sections/home/articles/components/article-card.tsx
import Image from "next/image";

type ArticleCardProps = {
	type: "large" | "small";
	image: string;
	title: string;
	description: string;
	postedAt: Date;
	author: string;
};

function formatDate(date: Date) {
	return date.toLocaleString("id-ID", {
		day: "numeric",
		month: "long",
		year: "numeric",
	});
}

export function ArticleCard(props: ArticleCardProps) {
	return (
		<div
			className={`shadow-lg rounded-2xl overflow-hidden flex ${
				props.type === "large" ? "flex-col row-span-2" : "flex-row"
			}`}
		>
			<div className="relative w-full h-auto min-h-[16rem]">
				<Image className="object-cover" src={props.image} alt={props.title} fill />
			</div>
			<div className="p-4">
				<span className="text-3xl leading-9 font-bold text-gray-600 block mb-2">{props.title}</span>
				<span className="text-xm leading-5 text-gray-600 block mb-4">
					{formatDate(props.postedAt)} | {props.author}
				</span>
				<p className="text-xl leading-7 text-gray-600">{props.description}</p>
			</div>
		</div>
	);
}
